routes/web.php
|--------------------------------------------------------------------------
|
*/
Route::get('/lang/{language}', 'LanguageController@switchLanguage')->name('switch_language');
/*
|--------------------------------------------------------------------------
| Roles
|--------------------------------------------------------------------------
|
*/
Route::resource('roles', 'RoleController');
/*
|--------------------------------------------------------------------------
| Permission
|--------------------------------------------------------------------------
|
*/
Route::resource('permissions', 'PermissionController');
/*
|--------------------------------------------------------------------------
| USERS
|--------------------------------------------------------------------------
|
*/

Route::resource('users', 'UserController');
Route::post('users_miscellaneous/index_search', 'UserController@search')->name('users_miscellaneous.index_search');

// Route::get(
//     'users_miscellaneous/delete_personal_image_ajax/{image_name}/{current_password}',
//     'UserController@deletePersonalImageAjax'
// )->name('users_miscellaneous.delete_personal_image_ajax');
// Route::get(
//     'users_miscellaneous/delete_personal_image_without_verification_ajax/{image_name}',
//     'UserController@deletePersonalImageWithoutVerificationAjax'
// )->name('users_miscellaneous.delete_personal_image_without_verification_ajax');
Route::get(
    'users_miscellaneous/index_users_not_verified_email',
    'UserController@indexUsersNotVerifiedEmail'
)->name('users_miscellaneous.index_users_not_verified_email');
Route::get(
    'users_miscellaneous/verify_user_email/{user}',
    'UserController@verifyUserEmail'
)->name('users_miscellaneous.verify_user_email');
Route::get(
    'users_miscellaneous/delete_personal_image_ajax/{project_file_id}',
    'UserController@deletePersonalImage'
)->name('users_miscellaneous.delete_personal_image_ajax');
/*
|--------------------------------------------------------------------------
| ROLE-USER
|--------------------------------------------------------------------------
|
*/
Route::resource('role_user', 'RoleUserController');

/*
|--------------------------------------------------------------------------
| Project Files
|--------------------------------------------------------------------------
|
*/
Route::resource('project_files', 'ProjectFileController');
Route::post(
    'project_files_miscellaneous/index_search',
    'ProjectFileController@search'
)->name('project_files_miscellaneous.index_search');

/*
|--------------------------------------------------------------------------
| Catalogs
|--------------------------------------------------------------------------
|
*/
Route::resource('catalogs', 'CatalogController');
Route::post(
    'catalogs_miscellaneous/index_search',
    'CatalogController@search'
)->name('catalogs_miscellaneous.index_search');
Route::get(
    'catalogs_miscellaneous/delete_file_ajax/{project_file_id}',
    'CatalogController@deleteFile'
)->name('catalogs_miscellaneous.delete_file_ajax');
Route::get(
    'catalogs_miscellaneous/download_file',
    'CatalogController@downloadFile'
)->name('catalogs_miscellaneous.download_file');
Route::get(
    'catalogs_miscellaneous/display_file',
    'CatalogController@displayFile'
)->name('catalogs_miscellaneous.display_file');
Route::get(
    'catalogs_miscellaneous/show_reservation_catalog/{catalog}',
    'CatalogController@showReservationCatalog'
)->name('catalogs_miscellaneous.show_reservation_catalog');
/*
|--------------------------------------------------------------------------
| Projects
|--------------------------------------------------------------------------
|
*/
Route::resource('projects', 'ProjectController');
Route::post(
    'projects_miscellaneous/index_search',
    'ProjectController@search'
)->name('projects_miscellaneous.index_search');
Route::get(
    'projects_miscellaneous/delete_image_ajax/{project_file_id}',
    'ProjectController@deleteImage'
)->name('projects_miscellaneous.delete_image_ajax');
Route::get(
    'projects_miscellaneous/filter_master_plan_image',
    'ProjectController@filterMasterPlanImage'
)->name('projects_miscellaneous.filter_master_plan_image');
Route::get('projects_miscellaneous/delete_logo', 'ProjectController@deleteLogo')->name('projects_miscellaneous.delete_logo');

/*
|--------------------------------------------------------------------------
| Phases
|--------------------------------------------------------------------------
|
*/
Route::resource('phases', 'PhaseController');
Route::post(
    'phases_miscellaneous/index_search',
    'PhaseController@search'
)->name('phases_miscellaneous.index_search');
Route::get(
    'phases_miscellaneous/get_project_names_ids',
    'PhaseController@getProjectNamesIds'
)->name('phases_miscellaneous.get_project_names_ids');
/*
|--------------------------------------------------------------------------
| Zones
|--------------------------------------------------------------------------
|
*/
Route::resource('zones', 'ZoneController');
Route::post(
    'zones_miscellaneous/index_search',
    'ZoneController@search'
)->name('zones_miscellaneous.index_search');
Route::get(
    'zones_miscellaneous/get_project_names_ids',
    'ZoneController@getProjectNamesIds'
)->name('zones_miscellaneous.get_project_names_ids');
/*
|--------------------------------------------------------------------------
| Blocks
|--------------------------------------------------------------------------
|
*/
Route::resource('blocks', 'BlockController');
Route::post(
    'blocks_miscellaneous/index_search',
    'BlockController@search'
)->name('blocks_miscellaneous.index_search');
Route::get(
    'blocks_miscellaneous/get_project_names_ids',
    'BlockController@getProjectNamesIds'
)->name('blocks_miscellaneous.get_project_names_ids');
/*
|--------------------------------------------------------------------------
| Unit Models
|--------------------------------------------------------------------------
|
*/
Route::resource('unit_models', 'UnitModelController');
Route::post(
    'unit_models_miscellaneous/index_search',
    'UnitModelController@search'
)->name('unit_models_miscellaneous.index_search');
/*
|--------------------------------------------------------------------------
| Units
|--------------------------------------------------------------------------
|
*/
Route::resource('units', 'UnitController');
Route::post(
    'units_miscellaneous/index_search',
    'UnitController@search'
)->name('units_miscellaneous.index_search');
Route::get(
    'units_miscellaneous/get_project_names_ids',
    'UnitController@getProjectNamesIds'
)->name('units_miscellaneous.get_project_names_ids');
Route::get(
    'units_miscellaneous/get_unit_model_names_ids',
    'UnitController@getUnitModelNamesIds'
)->name('units_miscellaneous.get_project_names_ids');
Route::get(
    'units_miscellaneous/show_as_pdf/{unit}',
    'UnitController@showAsPdf'
)->name('units_miscellaneous.show_as_pdf');
/*
|--------------------------------------------------------------------------
| Customers
|--------------------------------------------------------------------------
|
*/
Route::resource('customers', 'CustomerController');
Route::post(
    'customers_miscellaneous/index_search',
    'CustomerController@search'
)->name('customers_miscellaneous.index_search');

/*
|--------------------------------------------------------------------------
| Reservations
|--------------------------------------------------------------------------
|
*/
Route::resource('reservations', 'ReservationController');
Route::post(
    'reservations_miscellaneous/index_search',
    'ReservationController@search'
)->name('reservations_miscellaneous.index_search');
Route::get(
    'reservations_miscellaneous/get_unit_codes_ids',
    'ReservationController@getUnitCodesIds'
)->name('reservations_miscellaneous.get_unit_codes_ids');
Route::get(
    'reservations_miscellaneous/get_customer_names_ids',
    'ReservationController@getCustomerNamesIds'
)->name('reservations_miscellaneous.get_customer_names_ids');
Route::get(
    'reservations_miscellaneous/get_banks_names_ids',
    'ReservationController@getBanksNamesIds'
)->name('reservations_miscellaneous.get_banks_names_ids');

/*
|--------------------------------------------------------------------------
| Project User Assignment
|--------------------------------------------------------------------------
|
*/
Route::resource('project_user_assignments', 'ProjectUserAssignmentController');
Route::post(
    'project_user_assignments_miscellaneous/index_search',
    'ProjectUserAssignmentController@search'
)->name('project_user_assignments_miscellaneous.index_search');
Route::get(
    'project_user_assignments_miscellaneous/get_project_names_ids',
    'ProjectUserAssignmentController@getProjectNamesIds'
)->name('project_user_assignments_miscellaneous.get_project_names_ids');
Route::get(
    'project_user_assignments_miscellaneous/get_employee_names_ids',
    'ProjectUserAssignmentController@getEmployeeNamesIds'
)->name('project_user_assignments_miscellaneous.get_employee_names_ids');

/*
|--------------------------------------------------------------------------
| Dashboard
|--------------------------------------------------------------------------
|
*/
Route::get(
    'dashboard',
    'Dashboard\DashboardController@specifyUserDashboard'
)->name('dashboard');

/*
|--------------------------------------------------------------------------
| Developer Dashboard
|--------------------------------------------------------------------------
|
*/
Route::get('developer_dashboard/home', 'Dashboard\DeveloperDashboardController@home')
    ->name('developer_dashboard.home');
/*
|--------------------------------------------------------------------------
| Salesman Dashboard
|--------------------------------------------------------------------------
|
*/
Route::get('salesman_dashboard/home', 'Dashboard\SalesmanDashboardController@home')

app/Zone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Builder;

class Zone extends Model
{
    /*
    |--------------------------------------------------------------------------
    | Attributes
    |--------------------------------------------------------------------------
    |
    */
    protected $table = 'zones';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'notes',
        'creator_id',
        'last_updater_id',
        'project_id',
        'phase_id',
        'html_area_tag_coords',
        'net_suite_internal_id',
    ];

    /*
    |--------------------------------------------------------------------------
    | Constructors
    |--------------------------------------------------------------------------
    |
    */
    /*
    |--------------------------------------------------------------------------
    | Getters, Setters & Interface implementations
    |--------------------------------------------------------------------------
    |
    */

    /*
    |--------------------------------------------------------------------------
    | Accessors
    |--------------------------------------------------------------------------
    */

    public function getSelectedProjectNameIdAttribute()
    {
        $project = $this->project;
        if (!empty($project)) {
            $id = $project->id;
            $name = $project->name;
            if (!empty($id) && !empty($name)) {
                return ['id'=>$id, 'name'=>$name];
            }
        }
        return [];
    }

    public function getSelectedPhaseNameIdAttribute()
    {
        $phase = $this->phase;
        if (!empty($phase)) {
            $id = $phase->id;
            $name = $phase->name;
            if (!empty($id) && !empty($name)) {
                return ['id'=>$id, 'name'=>$name];
            }
        }
        return [];
    }

    public function getSelectedProjectPhasesNamesIdsAttribute()
    {
        $project = $this->project;
        if (request()->old('old_selected_phase_name') && request()->old('phase_id')) {
            return [request()->old('phase_id') => request()->old('old_selected_phase_name')];
        } elseif (!empty($project)) {
            $phases = $project->phases;
            if ($phases->isNotEmpty()) {
                return $phases->pluck('name', 'id');
            }
        }
        return [];
    }

    public function getSelectedProjectMasterPlanImageAttribute()
    {
        $project = $this->project;
        if (!empty($project)) {
            return $project->master_plan_image;
        }
        return '';
    }

    public function getZoneShowLinkAttribute()
    {
        if (!empty($this->id)) {
            return '<a href="'.action('ZoneController@show', ['id'=>$this->id]).'">'.$this->name.'</a>';
        }
        return '';
    }

    public function getZoneCatalogsShowLinksAttribute()
    {
        $zoneCatalogs = $this->catalogs;
        if ($zoneCatalogs->isNotEmpty()) {
            return $zoneCatalogs->pluck('catalog_show_link')->toArray();
        }
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    | Mutators
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | Relationships
    |--------------------------------------------------------------------------
    */

    /**
     * Getting the creator user who create this catalog.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return BelongsTo
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'creator_id', 'id');
    }

    /**
     * Getting the last updater user who update this catalog.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return BelongsTo
     */
    public function lastUpdater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'last_updater_id', 'id');
    }

    /**
     * Getting the project that are associated with this zone.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return BelongsTo
     */
    public function project()
    {
        return $this->belongsTo(Project::class, 'project_id', 'id');
    }

    /**
     * Getting the phase that are associated with this zone.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return BelongsTo
     */
    public function phase()
    {
        return $this->belongsTo(Phase::class, 'phase_id', 'id');
    }

    /**
     * Getting the units that are associated with this zone.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return void
     */
    public function units()
    {
        return $this->hasMany(Unit::class, 'zone_id', 'id');
    }

    /**
     * Getting the catalogs that are associated with this zone.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return void
     */
    public function catalogs()
    {
        return $this->hasMany(Catalog::class, 'zone_id', 'id');
    }

    /**
     * Getting the blocks that are associated with this zone.
     * Cardinality Constraint: 1:M.
     * Degree of Relationship: Binary
     *
     * @return void
     */
    public function blocks()
    {
        return $this->hasMany(Block::class, 'zone_id', 'id');
    }



    /*
    |--------------------------------------------------------------------------
    | Miscellaneous
    |--------------------------------------------------------------------------
    */

    public function search(Builder $builder, string $keyword)
    {
        return $builder->with('creator', 'project')
            ->where('name', 'like', "%$keyword%")
            ->orWhereHas('project', function ($query) use ($keyword) {
                $query->where('name', 'like', "%$keyword%");
            });
    }
}

resources/views/units/show/attributes.blade.php
<div class="col">
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <table class="table">
                    <tbody>
                        <tr class="table-danger">
                            <th scope="row" class="border-0">{{__('unit.project_name')}}</th>
                            <td class="border-0">{!!optional($unit->project)->project_show_link!!}</td>
                        </tr>
                        <tr class="table-danger">
                            <th scope="row" class="border-0">{{__('unit.phase_name')}}</th>
                            <td class="border-0">{!!optional($unit->phase)->phase_show_link!!}</td>
                        </tr>
                        <tr class="table-danger">
                            <th scope="row" class="border-0">{{__('unit.zone_name')}}</th>
                            <td class="border-0">{!!optional($unit->zone)->zone_show_link!!}</td>
                        </tr>
                        <tr class="table-danger">
                            <th scope="row" class="border-0">{{__('unit.block_name')}}</th>
                            <td class="border-0">{!!optional($unit->block)->block_show_link!!}</td>
                        </tr>
                        <tr class="table-danger">
                            <th scope="row" class="border-0">{{__('unit.unit_model_name')}}</th>
                            <td class="border-0">{!!optional($unit->unitModel)->unit_model_show_link!!}</td>
                        </tr>
                        <tr class="table-info">
                            <th scope="row" class="border-0">{{__('unit.id')}}</th>
                            <td class="border-0">{{$unit->id}}</td>
                        </tr>
                        <tr class="table-info">
                            <th scope="row" class="border-0">{{__('unit.code')}}</th>
                            <td class="border-0">{{$unit->code}}</td>
                        </tr>
                        <tr class="table-info">
                            <th scope="row" class="border-0">{{__('unit.status')}}</th>
                            <td class="border-0">
                                {{$unit->suitable_status}} {!! $unit->reservation_details !!}
                            </td>
                        </tr>
                        <tr class="table-info">
                            <th scope="row" class="border-0">{{__('unit.booking_amount')}}</th>
                            <td class="border-0">{{$unit->booking_amount_presentation}}</td>
                        </tr>
                        <tr class="table-info">
                            <th scope="row" class="border-0">{{__('unit.minimum_booking_amount')}}</th>
                            <td class="border-0">{{$unit->minimum_booking_amount_presentation}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit.land_number')}}</th>
                            <td class="border-0">{{$unit->land_number}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit.land_area')}}</th>
                            <td class="border-0">{{$unit->land_area}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit.built_up_area')}}</th>
                            <td class="border-0">{{$unit->built_up_area}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.built_up_area')}}</th>
                            <td class="border-0">{{optional($unit->unitModel)->built_up_area}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.number_of_bedrooms')}}</th>
                            <td class="border-0">{{$unit->number_of_bedrooms}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.number_of_bathrooms')}}</th>
                            <td class="border-0">{{$unit->number_of_bathrooms}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.number_of_kitchens')}}</th>
                            <td class="border-0">{{$unit->number_of_kitchens}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.number_of_floors')}}</th>
                            <td class="border-0">{{$unit->number_of_floors}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.number_of_balconies')}}</th>
                            <td class="border-0">{{$unit->number_of_balconies}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.number_of_elevators')}}</th>
                            <td class="border-0">{{$unit->number_of_elevators}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.has_pool')}}</th>
                            <td class="border-0">{{$unit->has_pool}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.pool_area')}}</th>
                            <td class="border-0">{{$unit->pool_area}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.has_garden')}}</th>
                            <td class="border-0">{{$unit->has_garden}}</td>
                        </tr>
                        <tr class="table-success">
                            <th scope="row" class="border-0">{{__('unit_model.garden_area')}}</th>
                            <td class="border-0">{{$unit->garden_area}}</td>
                        </tr>
                        <tr class="table-warning">
                            <th scope="row" class="border-0">{{__('unit.percentage_of_completion')}}</th>
                            <td class="border-0">{{$unit->percentage_of_completion}}</td>
                        </tr>
                        <tr class="table-warning">
                            <th scope="row" class="border-0">{{__('unit.developer_name')}}</th>
                            <td class="border-0">{{$unit->developer_name}}</td>
                        </tr>
                        <tr class="table-warning">
                            <th scope="row" class="border-0">{{__('unit.product_number')}}</th>
                            <td class="border-0">{{$unit->product_number}}</td>
                        </tr>
                        <tr class="table-warning">
                            <th scope="row" class="border-0">{{__('unit.land_price')}}</th>
                            <td class="border-0">{{$unit->land_price_presentation}}</td>
                        </tr>
                        <tr class="table-warning">
                            <th scope="row" class="border-0">{{__('unit.notes')}}</th>
                            <td class="border-0">{{$unit->notes}}</td>
                        </tr>
                        <tr class="table-dark">
                            <th scope="row" class="border-0">{{__('unit.sale_price')}}</th>
                            <td class="border-0">{{$unit->sale_price_presentation}}</td>
                        </tr>
                        <tr class="table-dark">
                            <th scope="row" class="border-0">{{__('unit.currency')}}</th>
                            <td class="border-0">{{$unit->currency}}</td>
                        </tr>




                        {{-- <tr>
                            <th scope="row" class="border-0">{{__('unit.construction_status')}}</th>
                        <td class="border-0">{{$unit->construction_status}}</td>
                        </tr> --}}

                        {{-- <tr>
                            <th scope="row" class="border-0">{{__('unit.is_for_sale')}}</th>
                        <td class="border-0">{{$unit->is_for_sale}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.sale_details')}}</th>
                            <td class="border-0">{{$unit->sale_details}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.date_of_sale')}}</th>
                            <td class="border-0">{{$unit->date_of_sale}}</td>
                        </tr> --}}
                        {{-- <tr>
                            <th scope="row" class="border-0">{{__('unit.is_for_rent')}}</th>
                        <td class="border-0">{{$unit->is_for_rent}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.rent_from')}}</th>
                            <td class="border-0">{{$unit->rent_from}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.rent_to')}}</th>
                            <td class="border-0">{{$unit->rent_to}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.rent_price')}}</th>
                            <td class="border-0">{{$unit->rent_price}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.rent_details')}}</th>
                            <td class="border-0">{{$unit->rent_details}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.unit_account_number')}}</th>
                            <td class="border-0">{{$unit->unit_account_number}}</td>
                        </tr> --}}
                        {{-- <tr>
                            <th scope="row" class="border-0">{{__('unit.direction')}}</th>
                        <td class="border-0">{{$unit->direction}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.floor_number')}}</th>
                            <td class="border-0">{{$unit->floor_number}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.address')}}</th>
                            <td class="border-0">{{$unit->address}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.latitude')}}</th>
                            <td class="border-0">{{$unit->latitude}}</td>
                        </tr>
                        <tr>
                            <th scope="row" class="border-0">{{__('unit.longitude')}}</th>
                            <td class="border-0">{{$unit->longitude}}</td>
                        </tr> --}}
                        {{-- <tr>
                            <th scope="row" class="border-0">{{__('unit.electricity_meter_number')}}</th>
                        <td class="border-0">{{$unit->electricity_meter_number}}</td>
                        </tr> --}}

                    </tbody>
                </table>
            </div>
        </div>
        <hr>
    </div>
</div>

resources/views/units/show/catalogs.blade.php
<div class="col">
    <div class="card">
        <div class="card-body">
            <h4 class="font-weight-bold text-center m-3"> الكتالوجات </h4>

            <table class="table table-hover" id="catalogs">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>{{__('catalog.id')}}</th>
                        <th>{{__('catalog.name')}}</th>
                        <th>{{__('catalog.description')}}</th>
                        <th>{{__('catalog.created_at')}}</th>
                        <th>{{__('catalog.creator_name')}}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($unit->catalogs as $catalogKey => $catalog)
                        <tr>
                            <td>{{$catalogKey+1}}</td>
                            <td>{{$catalog->id}}</td>
                            <td>
                                <a href="{{action('CatalogController@show', ['id'=>$catalog->id])}}">
                                    {{$catalog->name}}
                                </a>
                            </td>
                            <td>{{$catalog->description}}</td>
                            <td>{{$catalog->created_at}}</td>
                            <td>{{optional($catalog->creator)->name}}</td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
            <input id="data-table-search" type="hidden" value="{{__('data_table.search')}}">
            <input id="data-table-zero-record" type="hidden" value="{{__('data_table.zeroRecords')}}">
        </div>
    </div>
</div>